# Generated by Django 4.2 on 2024-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_imageslider_delete_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
