# Generated by Django 4.2 on 2024-12-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
